//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.18 at 01:36:20 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://norbertherczeg.me/projects/ican", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.noherczeg.ican.countries.io;
